# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160707_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_pickup',
            field=models.DateField(null=True),
        ),
    ]
