# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20160707_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_pickup',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
