# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20160708_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
