# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='Sykopro', max_length=1000, null=True),
        ),
    ]
