# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20160713_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount_paid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
