# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20160713_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='plastic',
            field=models.CharField(max_length=49, null=True),
        ),
    ]
